apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: test-app
  name: test-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      deploymentconfig: test-app
  template:
    metadata:
      labels:
        app: test-app
        deploymentconfig: test-app
      name: test-app
    spec:
      containers:
        - name: python-micro-service
          image: quay.io/sgahlot/test-app:0.5
          env:
            - name: TEST_OVERRIDE
              value: "{{ .Values.global.build.testing }}"
          #imagePullPolicy: Always
          ports:
          - containerPort: 5001
            name: http
            protocol: TCP
          volumeMounts:
          - mountPath: /var/www/html
            name: test-app-configmap
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5001
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5001
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: test-app-configmap
          configMap:
            defaultMode: 438
            name: test-app-configmap
